import= ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[scrolling]
history= 10000

[window]
title = ""
decorations = "Full"
padding = { x = 15, y = 0 }
dynamic_padding = true
opacity = 0.8
blur = true





[cursor]
style = { shape = "beam", blinking = "always"}
blink_interval= 500
vi_mode_style = { shape = "beam", blinking = "always"}
unfocused_hollow = false

[keyboard]
bindings = [
  { key= "V", mods= "Control", action= "Paste" }, 
  { key= "C", mods= "Control", action= "Copy" },
  { key= "C", mods= "Control | Shift", chars = "\u0003"}
]

[font]
size = 11.5
bold = {style = "Heavy"}
bold_italic = {style = "Heavy Italic"}
italic = {style = "Medium Italic"}
normal = {style = "Medium"}
